name: Deploy Next.js 13 to GitHub Pages

on:
  push:
    branches:
      - main
    # paths:
    #   - pgn-app
    #   - .github/workflows
env:
  - NEXT_PUBLIC_BASE_PATH: "/chess-tournament-games"
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          #cache: yarn

      - name: Install Dependencies
        run: yarn --cwd pgn-app --frozen-lockfile

      - name: Build Next.js App
        run: yarn --cwd pgn-app build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pgn-app/out
